version: '3.9'

services:

  proxy:
    image: nginx
    ports:
      - '80:80'
    depends_on:
      - backend

  backend:
    build: server
    restart: always
    command: 'python3 wsgi.py'
    ports:
      - '9000:9000'
    volumes:
      - ./docker/flask:/flask-server/vol
    environment:
      - FLASK_SERVER_ADDR
      - FLASK_SERVER_PORT
      - debug
    depends_on: 
      - mongo

  mongo:
    image: mongo
    hostname: mongodb_host
    environment:
      - MONGO_INNITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
      - MONGO_INITDB_DATABASE
    volumes: 
      - ./docker/mongodb:/database
    ports:
      - '27017:27017'

  mongo-express:
    image: mongo-express:0.54.0
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME
      - ME_CONFIG_MONGODB_ADMINPASSWORD
      - ME_CONFIG_MONGODB_URL
    ports:
      - '8081:8081'
